version: '3'

services:
  elasticsearch: # Elasticsearch Instance
    container_name: gs-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=zen
      - network.host=127.0.0.1
      - http.host=0.0.0.0
    ports: # Expose ElasticSearch ports
      - "9300:9300"
      - "9200:9200"

volumes:
  esdata:
