version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: docker.local/nginx:1.13.12
    ports:
      - 8002:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.web_app
    image: docker.local/flask-redis:1.0
    deploy:
      replicas: 6
    environment:
      - CONTAINER_HOST='{{.Node.Hostname}}'
    depends_on:
      - redis

  redis:
    image: "redis:alpine"